### ISSUE TITLE
Find previous solutions, try to use them as a baseline

### ISSUE THREAD

**Issue by vspolyakova** [twelveth/RumourEval2019#1]

**Comment by postrou** [comment]
[Starting point ](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0150989)

**Comment by postrou** [comment]
https://twitter.com/rumoureval

**Comment by postrou** [comment]
[More extensive task explaination + links to other useful (I guess) articles and **baselines**](https://www.researchgate.net/publication/327742640_RumourEval_2019_Determining_Rumour_Veracity_and_Support_for_Rumours)

**Comment by postrou** [comment]
[Baseline code from google group](https://github.com/kochkinaelena/RumourEval2019)

**Comment by postrou** [comment]
[Summary of current work on rumour verification](https://arxiv.org/pdf/1704.00656.pdf)
